name: 'Upload report to ContentStack'
description: 'Upload the index.html of a test report at provided path to ContentStack'
inputs:
  path: 
    description: Path to test folder containing index.html
    required: true

  management_token:
    description: 'Management Token'
    required: true

  api_key:
    description: 'Api Key'
    required: true

  parent_folder_uid:
    description: "Folder UID"
    required: false
    default: null

    
outputs:
  link:
    description: 'Link where the asset is uploaded'
runs:
  using: 'node16'
  main: 'dist/index.js'